name: Build and release executables

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build executables
      run: |
        pyinstaller --clean --onefile --icon "icon.ico" "updater.py"
      shell: bash
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this release:
          - Build executables for Windows, MacOS, and Linux
        draft: false
        prerelease: false
    - name: Upload executables
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ./dist/updater.exe
          ./dist/updater.dmg
          ./dist/updater
        asset_name: |
          updater-${{ github.ref }}-win64.exe
          updater-${{ github.ref }}-macos.dmg
          updater-${{ github.ref }}-linux64
        asset_content_type: |
          application/octet-stream
          application/octet-stream
          application/octet-stream